### ISSUE TITLE
Bug fixing on Application UI

### ISSUE THREAD

**Issue by saminur** [smarota17/JobTracker#18]
Application level UI had some bugs on grid view and data provider. 
Working on fixing the issues.

**Comment by smarota17** [comment]
What issues are you having? I don't see any issues on my end.

**Comment by smarota17** [comment]
Actually I see the issues. It's because the category field was deleted from jobs, so I went ahead and got rid of the lines of code calling job.getCategory(). Here's the commit where I fixed the bug: 25bc12ad25967c8598afccf3963b086fb569b8d3

Let me know if the issue still persists on your end, but I think we can close this issue now!
